### PR TITLE
Fix the shitty embed colours

### PR DESCRIPTION
**Pull request by luludotdev**
image

### CODE REVIEW

**Comment by sc2ad** [comment]
This looks good.

**Comment by RedBrumbler** [comment]
This looks good.

**Comment by Auros** [comment]
This looks good.

**Comment by Caeden117** [comment]
This looks good.

**Comment by ErisApps** [comment]
This looks good.

**Comment by legoandmars** [comment]
This looks good.

**Comment by monkeymanboy** [comment]
This looks good.

**Comment by Account57829** [comment]
This looks good.

**Comment by nike4613** [comment]
This looks good.

**Comment by FizzyApple12** [comment]
This looks good.

**Comment by rakso20000** [comment]
This looks good.

**Comment by raftario** [comment]
This looks good.

**Pull request merged**
